[2020-05-14 11:37:03] INFO [<module>: run_all.py, 7] ================================== 测试开始 ==================================
[2020-05-14 11:37:03] DEBUG [_new_conn: connectionpool.py, 225] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-05-14 11:37:03] DEBUG [_make_request: connectionpool.py, 437] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2020-05-14 11:37:03] DEBUG [_new_conn: connectionpool.py, 225] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-05-14 11:37:03] DEBUG [_make_request: connectionpool.py, 437] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2020-05-14 11:37:03] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2020-05-14 11:37:03] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2020-05-14 11:37:04] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2020-05-14 11:37:04] INFO [<module>: run_all.py, 14] ================================== 测试结束 ==================================
[2020-05-14 11:38:34] INFO [<module>: run_all.py, 7] ================================== 测试开始 ==================================
[2020-05-14 11:38:34] DEBUG [_new_conn: connectionpool.py, 225] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-05-14 11:38:34] DEBUG [_make_request: connectionpool.py, 437] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2020-05-14 11:38:34] DEBUG [_new_conn: connectionpool.py, 225] Starting new HTTP connection (1): 115.28.108.130:5000
[2020-05-14 11:38:34] DEBUG [_make_request: connectionpool.py, 437] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2020-05-14 11:38:34] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2020-05-14 11:38:34] DEBUG [query_db: db.py, 21] select * from user where name = '张三'
[2020-05-14 11:38:34] DEBUG [query_db: db.py, 21] select * from user where name = '范冰冰'
[2020-05-14 11:38:34] INFO [<module>: run_all.py, 14] ================================== 测试结束 ==================================
